---
port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: "110-299"

servers:
  server01:
    rack: CLAB
    adapters:
      - server_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet4, Ethernet4 ]
        switches: [leaf1, leaf2]
        profile: TENANT_A_B
        port_channel:
          state: present
          description: PortChannel4
          mode: active
  server02:
    rack: CLAB
    adapters:
      - server_ports: [Ethernet1, Ethernet2]
        switch_ports: [Ethernet4, Ethernet4 ]
        switches: [leaf3, leaf4]
        profile: TENANT_A_B
        port_channel:
          state: present
          description: PortChannel4
          mode: active