CVP_CONFIGLETS: {}
CVP_TOPOLOGY:
  DC1_FABRIC:
    parent_container: Tenant
  DC1_L3LEAFS:
    parent_container: DC1_FABRIC
  DC1_LEAF12:
    devices:
    - leaf1
    - leaf2
    parent_container: DC1_L3LEAFS
  DC1_LEAF34:
    devices:
    - leaf3
    - leaf4
    parent_container: DC1_L3LEAFS
  DC1_SPINES:
    devices:
    - spine1
    - spine2
    parent_container: DC1_FABRIC
changed: false
